### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by JustSeanC** [cguckes/ksp-chroma#15]
I followed the instructions and still nothing happens. It doesnt even show up in apps on synapse.

**Comment by cguckes** [comment]
The version of the colore library I use seems to be incompatible with the latest razer sdk. I will try to fix this, as soon as I find the time. I'm quite busy at the moment, but maybe I can fit it in someday.

**Comment by VirtualGaming1** [comment]
you should try now razer have updated there app. if you are using the new razer app from razer make sure you have chroma app enabled. cant wait for the next update of this.
