### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by fapcorn** [cguckes/ksp-chroma#18]
The "/" and "\" key lighting seem to be swapped, "\" lighting up red and "/" not lighting up at all, tho it's working in regular chroma lighting . Not sure if this is a compatibility or app problem. I'm using a Blackwidow V2 TE btw, also tried on the Razer Chroma Emulator (check screenshot). Dunno about other guys but this happens to me.

 Any help would be appreciated :) 
![untitled](https://user-images.githubusercontent.com/46871729/51451161-f5441a80-1d6e-11e9-8123-bb6ab6eaaee6.png)

**Comment by zer0Kerbal** [comment]
moved to zer0Kerbal/KSPChromaControl
