### ISSUE TITLE
I cant get it to work

### ISSUE THREAD

**Issue by monsterarth** [cguckes/ksp-chroma#20]
Sorry if im doing something wrong, but i just cant make it work... i downloaded and unzipped the folder "KSPChromaControl" in gamedata (right next to squad folder) and i have synapse 2 installed, i tried with other game and it do work... but kerbal isnt showing at synapse's apps

**Comment by spb1234** [comment]
So I was looking through stuff, as I am also trying to get this to work, and it looks like this is only able to work with ksp v1.3 and the current version of ksp is v1.6 so I think it needs to be updated again. That's my guess..

**Comment by cguckes** [comment]
@monsterarth, @spb1234 can you try with the current prerelease and give me feedback if it works as expected?

**Comment by OjGrooms** [comment]
Not sure if this is getting updated anymore, KSP has updated quite a bit. Having this installed breaks the game during load time.

**Comment by zer0Kerbal** [comment]
moved to zer0Kerbal/KSPChromaControl
