### ISSUE TITLE
goliathus chroma

### ISSUE THREAD

**Issue by disapointedavocardo** [cguckes/ksp-chroma#22]
I have recently installed KSP chroma and have noticed that the goliathus doesn't light up or show electric charge, I know on the razer website it says that it works with the firefly so it may be that less of the mat is lit but i assume that it just changes colour like the heat affect does. so can you please add support or at least have it show logo colours etc.

**Comment by cguckes** [comment]
Hi @disapointedavocardo,
I don't own a goliathus, so currently I can't test this. It's probably just a small piece of code. If you want to try your luck there, feel free to send me a pull request. Or send me a goliathus and I'll try ;-)

**Comment by zer0Kerbal** [comment]
moved to zer0Kerbal/KSPChromaControl
