### ISSUE TITLE
Support for multiple locale

### ISSUE THREAD

**Issue by Titozzz** [cguckes/ksp-chroma#6]
Hi man, I really like your Kerbal Mod, but since I have a french keyboard, some animations are messed up :disappointed: .

I never used the chroma SDK but I think there would be 2 main options : 
- detect the keyboard language (and layout) with Chroma SDK (if possible)
- detect the ingame setting

I'd like to help.

**Comment by cguckes** [comment]
Hi,

yeah, I figured that might be a problem. If you want to submit a pull request, you are of course welcome to. I think all you need to do is somehow figure out, which keyboard layout you use and replace the keyMapping dictionary in ColoreDrain. I would appreciate if the code would still work on my keyboard though :-), so some sort of detection would be great.

**Comment by cguckes** [comment]
Closed due to inactivity
