### ISSUE TITLE
All keys are lighting up randomly

### ISSUE THREAD

**Issue by Crosant** [cguckes/ksp-chroma#7]
In Version 1.1 All keys are lighting up randomly. Is this a problem of the new version of the game or is this the intended behavior?

**Comment by cguckes** [comment]
Can you make a photo of your keyboard? It should not be totally random. The pattern in flight mode and the one in editor mode, might look pretty random at first glance, but for all other screens it should look a little like the KSP logo (the rocket with the red line on blue background) minus the title...

**Comment by cguckes** [comment]
The bug has been reported to Razer, since the problem seems to be in the SDK. I'm closing this issue for now.
